### ISSUE TITLE
Env: stop using hosts as a method to check environment; use APP_ENV instead

### ISSUE THREAD

**Issue by cristianobaptista** [ponticlaro/bebop-common#6]
@huntercross What do you think?

**Comment by huntercross** [comment]
the benefit is ease of config?

When I am developing, I still use MAMP, so as long as I can set everything in a .env file, then I am fine. I would prefer everything to work with a .env file. 

Not sure, but i think this would mean we would be able to avoid branching right? We could avoid checking whether it was a dev site based on the url and instead could check for produciton or staging or development, right?

**Comment by cristianobaptista** [comment]
The benefit is that it makes not sense to maintain a list of hosts per environment. We always define the environment with `APP_ENV` anyway, so why not use that instead of a list that have to be updated in the source code?

We could still have the list of hosts for other specific uses, but not to determine if we're on a development, staging or production environment.

**Comment by huntercross** [comment]
sounds great. Where do we document this, since it would be required to run the app...Do we have an environment section in the standard readme?

We should probably have env.production.sample, env.staging.sample, env.development.sample or something like that

**Comment by cristianobaptista** [comment]
If you do not define `APP_ENV`, it will assumed you're on a `development` environment, but yeah, we need to document this.

We could have those `.env` files with just `APP_ENV` and other required (and maybe some optional) env vars as a heads up for anyone looking into the source code
